FROM node:20-alpine

WORKDIR /app

# Instalar pnpm
RUN npm install -g pnpm

# Copiar archivos raíz necesarios
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Copiar package.json de workspaces
COPY apps/web/package.json ./apps/web/package.json
COPY packages/shared/package.json ./packages/shared/package.json

# Instalar dependencias
RUN pnpm install

# Copiar resto del proyecto
COPY . .

# Ir al workspace web
WORKDIR /app/apps/web

EXPOSE 3000

CMD ["pnpm", "run", "dev"]